### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by maydaymarina** [seniorQAautomationEngineer/file_parser#1]
Please enhance the python method for updating dates in the XML file:

Make the method accept additional arguments: depart_tag, return_tag, date_format, 

so that the method can modify dates in either test_payload1.xml or test_payload2.xml (attached).

[test_payload2.xml.zip](https://github.com/seniorQAautomationEngineer/file_parser/files/5935664/test_payload2.xml.zip)

**Comment by AIengineerDev** [comment]
Done
